import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { ShoppingBag, Store } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { EmporiumProduct } from "@/lib/emporium.server";
import { useShopStore } from "@/store/shop-store";

export const Route = createFileRoute("/emporio")({ component: EmporiumPage });
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
function EmporiumPage() {
  const [products, setProducts] = useState<EmporiumProduct[]>([]); const [loading, setLoading] = useState(true); const add = useShopStore((state) => state.add);
  useEffect(() => { void fetch("/api/emporio", { cache: "no-store" }).then((response) => response.json()).then((data: { products?: EmporiumProduct[] }) => setProducts(data.products || [])).finally(() => setLoading(false)); }, []);
  const groups = useMemo(() => Object.entries(products.reduce<Record<string, EmporiumProduct[]>>((all, product) => { (all[product.category] ||= []).push(product); return all; }, {})), [products]);
  return <main><section className="border-b bg-gradient-to-br from-orange-soft via-background to-green-soft"><div className="container-page py-14 sm:py-20"><div className="mb-4 inline-flex items-center gap-2 rounded-full bg-card px-4 py-2 text-xs font-extrabold uppercase tracking-widest text-secondary shadow-sm"><Store className="h-4 w-4" />Empório agô</div><h1 className="max-w-3xl font-display text-4xl leading-tight sm:text-6xl">Produtos escolhidos para completar sua rotina.</h1><p className="mt-5 max-w-2xl text-base leading-relaxed text-muted-foreground sm:text-lg">Itens práticos, ingredientes e acompanhamentos em uma seção separada das nossas refeições.</p></div></section><section className="container-page py-10 sm:py-14">{loading ? <p className="text-muted-foreground">Carregando produtos...</p> : products.length === 0 ? <div className="rounded-3xl border border-dashed bg-card p-10 text-center"><Store className="mx-auto mb-3 h-10 w-10 text-primary" /><h2 className="font-display text-2xl">Novidades chegando</h2><p className="mt-2 text-muted-foreground">O Empório está sendo abastecido. Volte em breve.</p></div> : groups.map(([category, items]) => <section key={category} className="mb-12"><h2 className="mb-5 font-display text-3xl">{category}</h2><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{items?.map((product) => <article key={product.id} className="group overflow-hidden rounded-3xl border bg-card shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="aspect-[4/3] overflow-hidden bg-muted"><img src={product.image} alt={product.name} loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /></div><div className="p-5"><h3 className="font-display text-xl">{product.name}</h3><p className="mt-2 min-h-10 text-sm leading-relaxed text-muted-foreground">{product.shortDescription}</p><div className="mt-5 flex items-center justify-between gap-3"><div><div className="font-display text-xl text-primary-dark">{money.format(product.priceCents / 100)}</div><span className="text-[11px] text-muted-foreground">{product.stock > 0 ? `${product.stock} em estoque` : "Indisponível"}</span></div><Button size="icon" className="h-11 w-11 rounded-full" disabled={product.stock < 1} aria-label={`Adicionar ${product.name}`} onClick={() => add({ productId: `emporium:${product.id}`, name: product.name, image: product.image, price: product.priceCents / 100 })}><ShoppingBag className="h-4 w-4" /></Button></div></div></article>)}</div></section>)}</section></main>;
}
