/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as EmporioRouteImport } from './routes/emporio'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CentralAgons92xRouteImport } from './routes/central-agons-92x'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CentralAgons92xIndexRouteImport } from './routes/central-agons-92x.index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as PedidoConfirmadoRouteImport } from './routes/pedido.confirmado'
import { Route as ObjetivoSlugRouteImport } from './routes/objetivo.$slug'
import { Route as CentralAgons92xRedefinirSenhaRouteImport } from './routes/central-agons-92x.redefinir-senha'
import { Route as CentralAgons92xProdutosRouteImport } from './routes/central-agons-92x.produtos'
import { Route as CentralAgons92xPedidosRouteImport } from './routes/central-agons-92x.pedidos'
import { Route as CentralAgons92xObjetivosRouteImport } from './routes/central-agons-92x.objetivos'
import { Route as CentralAgons92xKitsRouteImport } from './routes/central-agons-92x.kits'
import { Route as CentralAgons92xHomeRouteImport } from './routes/central-agons-92x.home'
import { Route as CentralAgons92xEsqueciSenhaRouteImport } from './routes/central-agons-92x.esqueci-senha'
import { Route as CentralAgons92xEntrarRouteImport } from './routes/central-agons-92x.entrar'
import { Route as CentralAgons92xEmporioRouteImport } from './routes/central-agons-92x.emporio'
import { Route as CentralAgons92xCuponsRouteImport } from './routes/central-agons-92x.cupons'
import { Route as CentralAgons92xConteudoRouteImport } from './routes/central-agons-92x.conteudo'
import { Route as CentralAgons92xCategoriasRouteImport } from './routes/central-agons-92x.categorias'
import { Route as CentralAgons92xBannersRouteImport } from './routes/central-agons-92x.banners'
import { Route as CentralAgons92xAparenciaRouteImport } from './routes/central-agons-92x.aparencia'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe-webhook'
import { Route as ApiPasswordResetRouteImport } from './routes/api.password-reset'
import { Route as ApiOrdersRouteImport } from './routes/api.orders'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiEmporioRouteImport } from './routes/api.emporio'
import { Route as ApiCustomerSessionRouteImport } from './routes/api.customer-session'
import { Route as ApiCustomerRegisterRouteImport } from './routes/api.customer-register'
import { Route as ApiCustomerPasswordResetRouteImport } from './routes/api.customer-password-reset'
import { Route as ApiCheckoutRouteImport } from './routes/api.checkout'
import { Route as ApiAdminStateRouteImport } from './routes/api.admin-state'
import { Route as ApiAdminSessionRouteImport } from './routes/api.admin-session'
import { Route as ApiEmporioIdRouteImport } from './routes/api.emporio.$id'
import { Route as ApiCheckoutSessionIdRouteImport } from './routes/api.checkout-session.$id'

const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EmporioRoute = EmporioRouteImport.update({
  id: '/emporio',
  path: '/emporio',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralAgons92xRoute = CentralAgons92xRouteImport.update({
  id: '/central-agons-92x',
  path: '/central-agons-92x',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralAgons92xIndexRoute = CentralAgons92xIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoConfirmadoRoute = PedidoConfirmadoRouteImport.update({
  id: '/pedido/confirmado',
  path: '/pedido/confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjetivoSlugRoute = ObjetivoSlugRouteImport.update({
  id: '/objetivo/$slug',
  path: '/objetivo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralAgons92xRedefinirSenhaRoute =
  CentralAgons92xRedefinirSenhaRouteImport.update({
    id: '/redefinir-senha',
    path: '/redefinir-senha',
    getParentRoute: () => CentralAgons92xRoute,
  } as any)
const CentralAgons92xProdutosRoute = CentralAgons92xProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const CentralAgons92xPedidosRoute = CentralAgons92xPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const CentralAgons92xObjetivosRoute =
  CentralAgons92xObjetivosRouteImport.update({
    id: '/objetivos',
    path: '/objetivos',
    getParentRoute: () => CentralAgons92xRoute,
  } as any)
const CentralAgons92xKitsRoute = CentralAgons92xKitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const CentralAgons92xHomeRoute = CentralAgons92xHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const CentralAgons92xEsqueciSenhaRoute =
  CentralAgons92xEsqueciSenhaRouteImport.update({
    id: '/esqueci-senha',
    path: '/esqueci-senha',
    getParentRoute: () => CentralAgons92xRoute,
  } as any)
const CentralAgons92xEntrarRoute = CentralAgons92xEntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const CentralAgons92xEmporioRoute = CentralAgons92xEmporioRouteImport.update({
  id: '/emporio',
  path: '/emporio',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const CentralAgons92xCuponsRoute = CentralAgons92xCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const CentralAgons92xConteudoRoute = CentralAgons92xConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const CentralAgons92xCategoriasRoute =
  CentralAgons92xCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => CentralAgons92xRoute,
  } as any)
const CentralAgons92xBannersRoute = CentralAgons92xBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const CentralAgons92xAparenciaRoute =
  CentralAgons92xAparenciaRouteImport.update({
    id: '/aparencia',
    path: '/aparencia',
    getParentRoute: () => CentralAgons92xRoute,
  } as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPasswordResetRoute = ApiPasswordResetRouteImport.update({
  id: '/api/password-reset',
  path: '/api/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmporioRoute = ApiEmporioRouteImport.update({
  id: '/api/emporio',
  path: '/api/emporio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerSessionRoute = ApiCustomerSessionRouteImport.update({
  id: '/api/customer-session',
  path: '/api/customer-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerRegisterRoute = ApiCustomerRegisterRouteImport.update({
  id: '/api/customer-register',
  path: '/api/customer-register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerPasswordResetRoute =
  ApiCustomerPasswordResetRouteImport.update({
    id: '/api/customer-password-reset',
    path: '/api/customer-password-reset',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStateRoute = ApiAdminStateRouteImport.update({
  id: '/api/admin-state',
  path: '/api/admin-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSessionRoute = ApiAdminSessionRouteImport.update({
  id: '/api/admin-session',
  path: '/api/admin-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmporioIdRoute = ApiEmporioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiEmporioRoute,
} as any)
const ApiCheckoutSessionIdRoute = ApiCheckoutSessionIdRouteImport.update({
  id: '/api/checkout-session/$id',
  path: '/api/checkout-session/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/central-agons-92x': typeof CentralAgons92xRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/emporio': typeof EmporioRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/api/admin-session': typeof ApiAdminSessionRoute
  '/api/admin-state': typeof ApiAdminStateRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/customer-password-reset': typeof ApiCustomerPasswordResetRoute
  '/api/customer-register': typeof ApiCustomerRegisterRoute
  '/api/customer-session': typeof ApiCustomerSessionRoute
  '/api/emporio': typeof ApiEmporioRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/password-reset': typeof ApiPasswordResetRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/central-agons-92x/aparencia': typeof CentralAgons92xAparenciaRoute
  '/central-agons-92x/banners': typeof CentralAgons92xBannersRoute
  '/central-agons-92x/categorias': typeof CentralAgons92xCategoriasRoute
  '/central-agons-92x/conteudo': typeof CentralAgons92xConteudoRoute
  '/central-agons-92x/cupons': typeof CentralAgons92xCuponsRoute
  '/central-agons-92x/emporio': typeof CentralAgons92xEmporioRoute
  '/central-agons-92x/entrar': typeof CentralAgons92xEntrarRoute
  '/central-agons-92x/esqueci-senha': typeof CentralAgons92xEsqueciSenhaRoute
  '/central-agons-92x/home': typeof CentralAgons92xHomeRoute
  '/central-agons-92x/kits': typeof CentralAgons92xKitsRoute
  '/central-agons-92x/objetivos': typeof CentralAgons92xObjetivosRoute
  '/central-agons-92x/pedidos': typeof CentralAgons92xPedidosRoute
  '/central-agons-92x/produtos': typeof CentralAgons92xProdutosRoute
  '/central-agons-92x/redefinir-senha': typeof CentralAgons92xRedefinirSenhaRoute
  '/objetivo/$slug': typeof ObjetivoSlugRoute
  '/pedido/confirmado': typeof PedidoConfirmadoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/central-agons-92x/': typeof CentralAgons92xIndexRoute
  '/api/checkout-session/$id': typeof ApiCheckoutSessionIdRoute
  '/api/emporio/$id': typeof ApiEmporioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/emporio': typeof EmporioRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/api/admin-session': typeof ApiAdminSessionRoute
  '/api/admin-state': typeof ApiAdminStateRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/customer-password-reset': typeof ApiCustomerPasswordResetRoute
  '/api/customer-register': typeof ApiCustomerRegisterRoute
  '/api/customer-session': typeof ApiCustomerSessionRoute
  '/api/emporio': typeof ApiEmporioRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/password-reset': typeof ApiPasswordResetRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/central-agons-92x/aparencia': typeof CentralAgons92xAparenciaRoute
  '/central-agons-92x/banners': typeof CentralAgons92xBannersRoute
  '/central-agons-92x/categorias': typeof CentralAgons92xCategoriasRoute
  '/central-agons-92x/conteudo': typeof CentralAgons92xConteudoRoute
  '/central-agons-92x/cupons': typeof CentralAgons92xCuponsRoute
  '/central-agons-92x/emporio': typeof CentralAgons92xEmporioRoute
  '/central-agons-92x/entrar': typeof CentralAgons92xEntrarRoute
  '/central-agons-92x/esqueci-senha': typeof CentralAgons92xEsqueciSenhaRoute
  '/central-agons-92x/home': typeof CentralAgons92xHomeRoute
  '/central-agons-92x/kits': typeof CentralAgons92xKitsRoute
  '/central-agons-92x/objetivos': typeof CentralAgons92xObjetivosRoute
  '/central-agons-92x/pedidos': typeof CentralAgons92xPedidosRoute
  '/central-agons-92x/produtos': typeof CentralAgons92xProdutosRoute
  '/central-agons-92x/redefinir-senha': typeof CentralAgons92xRedefinirSenhaRoute
  '/objetivo/$slug': typeof ObjetivoSlugRoute
  '/pedido/confirmado': typeof PedidoConfirmadoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/central-agons-92x': typeof CentralAgons92xIndexRoute
  '/api/checkout-session/$id': typeof ApiCheckoutSessionIdRoute
  '/api/emporio/$id': typeof ApiEmporioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/central-agons-92x': typeof CentralAgons92xRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/emporio': typeof EmporioRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/api/admin-session': typeof ApiAdminSessionRoute
  '/api/admin-state': typeof ApiAdminStateRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/customer-password-reset': typeof ApiCustomerPasswordResetRoute
  '/api/customer-register': typeof ApiCustomerRegisterRoute
  '/api/customer-session': typeof ApiCustomerSessionRoute
  '/api/emporio': typeof ApiEmporioRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/password-reset': typeof ApiPasswordResetRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/central-agons-92x/aparencia': typeof CentralAgons92xAparenciaRoute
  '/central-agons-92x/banners': typeof CentralAgons92xBannersRoute
  '/central-agons-92x/categorias': typeof CentralAgons92xCategoriasRoute
  '/central-agons-92x/conteudo': typeof CentralAgons92xConteudoRoute
  '/central-agons-92x/cupons': typeof CentralAgons92xCuponsRoute
  '/central-agons-92x/emporio': typeof CentralAgons92xEmporioRoute
  '/central-agons-92x/entrar': typeof CentralAgons92xEntrarRoute
  '/central-agons-92x/esqueci-senha': typeof CentralAgons92xEsqueciSenhaRoute
  '/central-agons-92x/home': typeof CentralAgons92xHomeRoute
  '/central-agons-92x/kits': typeof CentralAgons92xKitsRoute
  '/central-agons-92x/objetivos': typeof CentralAgons92xObjetivosRoute
  '/central-agons-92x/pedidos': typeof CentralAgons92xPedidosRoute
  '/central-agons-92x/produtos': typeof CentralAgons92xProdutosRoute
  '/central-agons-92x/redefinir-senha': typeof CentralAgons92xRedefinirSenhaRoute
  '/objetivo/$slug': typeof ObjetivoSlugRoute
  '/pedido/confirmado': typeof PedidoConfirmadoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/central-agons-92x/': typeof CentralAgons92xIndexRoute
  '/api/checkout-session/$id': typeof ApiCheckoutSessionIdRoute
  '/api/emporio/$id': typeof ApiEmporioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/central-agons-92x'
    | '/checkout'
    | '/emporio'
    | '/esqueci-senha'
    | '/login'
    | '/minha-conta'
    | '/redefinir-senha'
    | '/api/admin-session'
    | '/api/admin-state'
    | '/api/checkout'
    | '/api/customer-password-reset'
    | '/api/customer-register'
    | '/api/customer-session'
    | '/api/emporio'
    | '/api/health'
    | '/api/orders'
    | '/api/password-reset'
    | '/api/stripe-webhook'
    | '/categoria/$slug'
    | '/central-agons-92x/aparencia'
    | '/central-agons-92x/banners'
    | '/central-agons-92x/categorias'
    | '/central-agons-92x/conteudo'
    | '/central-agons-92x/cupons'
    | '/central-agons-92x/emporio'
    | '/central-agons-92x/entrar'
    | '/central-agons-92x/esqueci-senha'
    | '/central-agons-92x/home'
    | '/central-agons-92x/kits'
    | '/central-agons-92x/objetivos'
    | '/central-agons-92x/pedidos'
    | '/central-agons-92x/produtos'
    | '/central-agons-92x/redefinir-senha'
    | '/objetivo/$slug'
    | '/pedido/confirmado'
    | '/produto/$slug'
    | '/central-agons-92x/'
    | '/api/checkout-session/$id'
    | '/api/emporio/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/checkout'
    | '/emporio'
    | '/esqueci-senha'
    | '/login'
    | '/minha-conta'
    | '/redefinir-senha'
    | '/api/admin-session'
    | '/api/admin-state'
    | '/api/checkout'
    | '/api/customer-password-reset'
    | '/api/customer-register'
    | '/api/customer-session'
    | '/api/emporio'
    | '/api/health'
    | '/api/orders'
    | '/api/password-reset'
    | '/api/stripe-webhook'
    | '/categoria/$slug'
    | '/central-agons-92x/aparencia'
    | '/central-agons-92x/banners'
    | '/central-agons-92x/categorias'
    | '/central-agons-92x/conteudo'
    | '/central-agons-92x/cupons'
    | '/central-agons-92x/emporio'
    | '/central-agons-92x/entrar'
    | '/central-agons-92x/esqueci-senha'
    | '/central-agons-92x/home'
    | '/central-agons-92x/kits'
    | '/central-agons-92x/objetivos'
    | '/central-agons-92x/pedidos'
    | '/central-agons-92x/produtos'
    | '/central-agons-92x/redefinir-senha'
    | '/objetivo/$slug'
    | '/pedido/confirmado'
    | '/produto/$slug'
    | '/central-agons-92x'
    | '/api/checkout-session/$id'
    | '/api/emporio/$id'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/central-agons-92x'
    | '/checkout'
    | '/emporio'
    | '/esqueci-senha'
    | '/login'
    | '/minha-conta'
    | '/redefinir-senha'
    | '/api/admin-session'
    | '/api/admin-state'
    | '/api/checkout'
    | '/api/customer-password-reset'
    | '/api/customer-register'
    | '/api/customer-session'
    | '/api/emporio'
    | '/api/health'
    | '/api/orders'
    | '/api/password-reset'
    | '/api/stripe-webhook'
    | '/categoria/$slug'
    | '/central-agons-92x/aparencia'
    | '/central-agons-92x/banners'
    | '/central-agons-92x/categorias'
    | '/central-agons-92x/conteudo'
    | '/central-agons-92x/cupons'
    | '/central-agons-92x/emporio'
    | '/central-agons-92x/entrar'
    | '/central-agons-92x/esqueci-senha'
    | '/central-agons-92x/home'
    | '/central-agons-92x/kits'
    | '/central-agons-92x/objetivos'
    | '/central-agons-92x/pedidos'
    | '/central-agons-92x/produtos'
    | '/central-agons-92x/redefinir-senha'
    | '/objetivo/$slug'
    | '/pedido/confirmado'
    | '/produto/$slug'
    | '/central-agons-92x/'
    | '/api/checkout-session/$id'
    | '/api/emporio/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CentralAgons92xRoute: typeof CentralAgons92xRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  EmporioRoute: typeof EmporioRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  MinhaContaRoute: typeof MinhaContaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  ApiAdminSessionRoute: typeof ApiAdminSessionRoute
  ApiAdminStateRoute: typeof ApiAdminStateRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiCustomerPasswordResetRoute: typeof ApiCustomerPasswordResetRoute
  ApiCustomerRegisterRoute: typeof ApiCustomerRegisterRoute
  ApiCustomerSessionRoute: typeof ApiCustomerSessionRoute
  ApiEmporioRoute: typeof ApiEmporioRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiPasswordResetRoute: typeof ApiPasswordResetRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ObjetivoSlugRoute: typeof ObjetivoSlugRoute
  PedidoConfirmadoRoute: typeof PedidoConfirmadoRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiCheckoutSessionIdRoute: typeof ApiCheckoutSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emporio': {
      id: '/emporio'
      path: '/emporio'
      fullPath: '/emporio'
      preLoaderRoute: typeof EmporioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central-agons-92x': {
      id: '/central-agons-92x'
      path: '/central-agons-92x'
      fullPath: '/central-agons-92x'
      preLoaderRoute: typeof CentralAgons92xRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central-agons-92x/': {
      id: '/central-agons-92x/'
      path: '/'
      fullPath: '/central-agons-92x/'
      preLoaderRoute: typeof CentralAgons92xIndexRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/confirmado': {
      id: '/pedido/confirmado'
      path: '/pedido/confirmado'
      fullPath: '/pedido/confirmado'
      preLoaderRoute: typeof PedidoConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objetivo/$slug': {
      id: '/objetivo/$slug'
      path: '/objetivo/$slug'
      fullPath: '/objetivo/$slug'
      preLoaderRoute: typeof ObjetivoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central-agons-92x/redefinir-senha': {
      id: '/central-agons-92x/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/central-agons-92x/redefinir-senha'
      preLoaderRoute: typeof CentralAgons92xRedefinirSenhaRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/produtos': {
      id: '/central-agons-92x/produtos'
      path: '/produtos'
      fullPath: '/central-agons-92x/produtos'
      preLoaderRoute: typeof CentralAgons92xProdutosRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/pedidos': {
      id: '/central-agons-92x/pedidos'
      path: '/pedidos'
      fullPath: '/central-agons-92x/pedidos'
      preLoaderRoute: typeof CentralAgons92xPedidosRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/objetivos': {
      id: '/central-agons-92x/objetivos'
      path: '/objetivos'
      fullPath: '/central-agons-92x/objetivos'
      preLoaderRoute: typeof CentralAgons92xObjetivosRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/kits': {
      id: '/central-agons-92x/kits'
      path: '/kits'
      fullPath: '/central-agons-92x/kits'
      preLoaderRoute: typeof CentralAgons92xKitsRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/home': {
      id: '/central-agons-92x/home'
      path: '/home'
      fullPath: '/central-agons-92x/home'
      preLoaderRoute: typeof CentralAgons92xHomeRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/esqueci-senha': {
      id: '/central-agons-92x/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/central-agons-92x/esqueci-senha'
      preLoaderRoute: typeof CentralAgons92xEsqueciSenhaRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/entrar': {
      id: '/central-agons-92x/entrar'
      path: '/entrar'
      fullPath: '/central-agons-92x/entrar'
      preLoaderRoute: typeof CentralAgons92xEntrarRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/emporio': {
      id: '/central-agons-92x/emporio'
      path: '/emporio'
      fullPath: '/central-agons-92x/emporio'
      preLoaderRoute: typeof CentralAgons92xEmporioRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/cupons': {
      id: '/central-agons-92x/cupons'
      path: '/cupons'
      fullPath: '/central-agons-92x/cupons'
      preLoaderRoute: typeof CentralAgons92xCuponsRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/conteudo': {
      id: '/central-agons-92x/conteudo'
      path: '/conteudo'
      fullPath: '/central-agons-92x/conteudo'
      preLoaderRoute: typeof CentralAgons92xConteudoRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/categorias': {
      id: '/central-agons-92x/categorias'
      path: '/categorias'
      fullPath: '/central-agons-92x/categorias'
      preLoaderRoute: typeof CentralAgons92xCategoriasRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/banners': {
      id: '/central-agons-92x/banners'
      path: '/banners'
      fullPath: '/central-agons-92x/banners'
      preLoaderRoute: typeof CentralAgons92xBannersRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/aparencia': {
      id: '/central-agons-92x/aparencia'
      path: '/aparencia'
      fullPath: '/central-agons-92x/aparencia'
      preLoaderRoute: typeof CentralAgons92xAparenciaRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/password-reset': {
      id: '/api/password-reset'
      path: '/api/password-reset'
      fullPath: '/api/password-reset'
      preLoaderRoute: typeof ApiPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/emporio': {
      id: '/api/emporio'
      path: '/api/emporio'
      fullPath: '/api/emporio'
      preLoaderRoute: typeof ApiEmporioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-session': {
      id: '/api/customer-session'
      path: '/api/customer-session'
      fullPath: '/api/customer-session'
      preLoaderRoute: typeof ApiCustomerSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-register': {
      id: '/api/customer-register'
      path: '/api/customer-register'
      fullPath: '/api/customer-register'
      preLoaderRoute: typeof ApiCustomerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-password-reset': {
      id: '/api/customer-password-reset'
      path: '/api/customer-password-reset'
      fullPath: '/api/customer-password-reset'
      preLoaderRoute: typeof ApiCustomerPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-state': {
      id: '/api/admin-state'
      path: '/api/admin-state'
      fullPath: '/api/admin-state'
      preLoaderRoute: typeof ApiAdminStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-session': {
      id: '/api/admin-session'
      path: '/api/admin-session'
      fullPath: '/api/admin-session'
      preLoaderRoute: typeof ApiAdminSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/emporio/$id': {
      id: '/api/emporio/$id'
      path: '/$id'
      fullPath: '/api/emporio/$id'
      preLoaderRoute: typeof ApiEmporioIdRouteImport
      parentRoute: typeof ApiEmporioRoute
    }
    '/api/checkout-session/$id': {
      id: '/api/checkout-session/$id'
      path: '/api/checkout-session/$id'
      fullPath: '/api/checkout-session/$id'
      preLoaderRoute: typeof ApiCheckoutSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CentralAgons92xRouteChildren {
  CentralAgons92xAparenciaRoute: typeof CentralAgons92xAparenciaRoute
  CentralAgons92xBannersRoute: typeof CentralAgons92xBannersRoute
  CentralAgons92xCategoriasRoute: typeof CentralAgons92xCategoriasRoute
  CentralAgons92xConteudoRoute: typeof CentralAgons92xConteudoRoute
  CentralAgons92xCuponsRoute: typeof CentralAgons92xCuponsRoute
  CentralAgons92xEmporioRoute: typeof CentralAgons92xEmporioRoute
  CentralAgons92xEntrarRoute: typeof CentralAgons92xEntrarRoute
  CentralAgons92xEsqueciSenhaRoute: typeof CentralAgons92xEsqueciSenhaRoute
  CentralAgons92xHomeRoute: typeof CentralAgons92xHomeRoute
  CentralAgons92xKitsRoute: typeof CentralAgons92xKitsRoute
  CentralAgons92xObjetivosRoute: typeof CentralAgons92xObjetivosRoute
  CentralAgons92xPedidosRoute: typeof CentralAgons92xPedidosRoute
  CentralAgons92xProdutosRoute: typeof CentralAgons92xProdutosRoute
  CentralAgons92xRedefinirSenhaRoute: typeof CentralAgons92xRedefinirSenhaRoute
  CentralAgons92xIndexRoute: typeof CentralAgons92xIndexRoute
}

const CentralAgons92xRouteChildren: CentralAgons92xRouteChildren = {
  CentralAgons92xAparenciaRoute: CentralAgons92xAparenciaRoute,
  CentralAgons92xBannersRoute: CentralAgons92xBannersRoute,
  CentralAgons92xCategoriasRoute: CentralAgons92xCategoriasRoute,
  CentralAgons92xConteudoRoute: CentralAgons92xConteudoRoute,
  CentralAgons92xCuponsRoute: CentralAgons92xCuponsRoute,
  CentralAgons92xEmporioRoute: CentralAgons92xEmporioRoute,
  CentralAgons92xEntrarRoute: CentralAgons92xEntrarRoute,
  CentralAgons92xEsqueciSenhaRoute: CentralAgons92xEsqueciSenhaRoute,
  CentralAgons92xHomeRoute: CentralAgons92xHomeRoute,
  CentralAgons92xKitsRoute: CentralAgons92xKitsRoute,
  CentralAgons92xObjetivosRoute: CentralAgons92xObjetivosRoute,
  CentralAgons92xPedidosRoute: CentralAgons92xPedidosRoute,
  CentralAgons92xProdutosRoute: CentralAgons92xProdutosRoute,
  CentralAgons92xRedefinirSenhaRoute: CentralAgons92xRedefinirSenhaRoute,
  CentralAgons92xIndexRoute: CentralAgons92xIndexRoute,
}

const CentralAgons92xRouteWithChildren = CentralAgons92xRoute._addFileChildren(
  CentralAgons92xRouteChildren,
)

interface ApiEmporioRouteChildren {
  ApiEmporioIdRoute: typeof ApiEmporioIdRoute
}

const ApiEmporioRouteChildren: ApiEmporioRouteChildren = {
  ApiEmporioIdRoute: ApiEmporioIdRoute,
}

const ApiEmporioRouteWithChildren = ApiEmporioRoute._addFileChildren(
  ApiEmporioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CentralAgons92xRoute: CentralAgons92xRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  EmporioRoute: EmporioRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  MinhaContaRoute: MinhaContaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  ApiAdminSessionRoute: ApiAdminSessionRoute,
  ApiAdminStateRoute: ApiAdminStateRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiCustomerPasswordResetRoute: ApiCustomerPasswordResetRoute,
  ApiCustomerRegisterRoute: ApiCustomerRegisterRoute,
  ApiCustomerSessionRoute: ApiCustomerSessionRoute,
  ApiEmporioRoute: ApiEmporioRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiPasswordResetRoute: ApiPasswordResetRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ObjetivoSlugRoute: ObjetivoSlugRoute,
  PedidoConfirmadoRoute: PedidoConfirmadoRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiCheckoutSessionIdRoute: ApiCheckoutSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
