/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as EntregasRouteImport } from './routes/entregas'
import { Route as EmporioRouteImport } from './routes/emporio'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CentralAgons92xRouteImport } from './routes/central-agons-92x'
import { Route as CardapioRouteImport } from './routes/cardapio'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CentralAgons92xIndexRouteImport } from './routes/central-agons-92x.index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as PedidoConfirmadoRouteImport } from './routes/pedido.confirmado'
import { Route as ObjetivoSlugRouteImport } from './routes/objetivo.$slug'
import { Route as KitSlugRouteImport } from './routes/kit.$slug'
import { Route as CentralAgons92xRelatoriosRouteImport } from './routes/central-agons-92x.relatorios'
import { Route as CentralAgons92xRedefinirSenhaRouteImport } from './routes/central-agons-92x.redefinir-senha'
import { Route as CentralAgons92xProdutosRouteImport } from './routes/central-agons-92x.produtos'
import { Route as CentralAgons92xProducaoRouteImport } from './routes/central-agons-92x.producao'
import { Route as CentralAgons92xPedidosRouteImport } from './routes/central-agons-92x.pedidos'
import { Route as CentralAgons92xObjetivosRouteImport } from './routes/central-agons-92x.objetivos'
import { Route as CentralAgons92xLogisticaRouteImport } from './routes/central-agons-92x.logistica'
import { Route as CentralAgons92xKitsRouteImport } from './routes/central-agons-92x.kits'
import { Route as CentralAgons92xHomeRouteImport } from './routes/central-agons-92x.home'
import { Route as CentralAgons92xEsqueciSenhaRouteImport } from './routes/central-agons-92x.esqueci-senha'
import { Route as CentralAgons92xEntrarRouteImport } from './routes/central-agons-92x.entrar'
import { Route as CentralAgons92xEmporioRouteImport } from './routes/central-agons-92x.emporio'
import { Route as CentralAgons92xCuponsRouteImport } from './routes/central-agons-92x.cupons'
import { Route as CentralAgons92xConteudoRouteImport } from './routes/central-agons-92x.conteudo'
import { Route as CentralAgons92xClientesRouteImport } from './routes/central-agons-92x.clientes'
import { Route as CentralAgons92xCategoriasRouteImport } from './routes/central-agons-92x.categorias'
import { Route as CentralAgons92xCalendarioRouteImport } from './routes/central-agons-92x.calendario'
import { Route as CentralAgons92xBannersRouteImport } from './routes/central-agons-92x.banners'
import { Route as CentralAgons92xAparenciaRouteImport } from './routes/central-agons-92x.aparencia'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe-webhook'
import { Route as ApiPasswordResetRouteImport } from './routes/api.password-reset'
import { Route as ApiOrdersRouteImport } from './routes/api.orders'
import { Route as ApiMediaRouteImport } from './routes/api.media'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiEmporioRouteImport } from './routes/api.emporio'
import { Route as ApiDeliveryCalendarRouteImport } from './routes/api.delivery-calendar'
import { Route as ApiCustomerSessionRouteImport } from './routes/api.customer-session'
import { Route as ApiCustomerRegisterRouteImport } from './routes/api.customer-register'
import { Route as ApiCustomerPasswordResetRouteImport } from './routes/api.customer-password-reset'
import { Route as ApiCustomerAccountRouteImport } from './routes/api.customer-account'
import { Route as ApiCheckoutRouteImport } from './routes/api.checkout'
import { Route as ApiAdminStateRouteImport } from './routes/api.admin-state'
import { Route as ApiAdminSessionRouteImport } from './routes/api.admin-session'
import { Route as ApiAdminOperationsRouteImport } from './routes/api.admin-operations'
import { Route as ApiMediaIdRouteImport } from './routes/api.media.$id'
import { Route as ApiEmporioIdRouteImport } from './routes/api.emporio.$id'
import { Route as ApiCheckoutSessionIdRouteImport } from './routes/api.checkout-session.$id'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregasRoute = EntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmporioRoute = EmporioRouteImport.update({
  id: '/emporio',
  path: '/emporio',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralAgons92xRoute = CentralAgons92xRouteImport.update({
  id: '/central-agons-92x',
  path: '/central-agons-92x',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioRoute = CardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralAgons92xIndexRoute = CentralAgons92xIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoConfirmadoRoute = PedidoConfirmadoRouteImport.update({
  id: '/pedido/confirmado',
  path: '/pedido/confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjetivoSlugRoute = ObjetivoSlugRouteImport.update({
  id: '/objetivo/$slug',
  path: '/objetivo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KitSlugRoute = KitSlugRouteImport.update({
  id: '/kit/$slug',
  path: '/kit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralAgons92xRelatoriosRoute =
  CentralAgons92xRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => CentralAgons92xRoute,
  } as any)
const CentralAgons92xRedefinirSenhaRoute =
  CentralAgons92xRedefinirSenhaRouteImport.update({
    id: '/redefinir-senha',
    path: '/redefinir-senha',
    getParentRoute: () => CentralAgons92xRoute,
  } as any)
const CentralAgons92xProdutosRoute = CentralAgons92xProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const CentralAgons92xProducaoRoute = CentralAgons92xProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const CentralAgons92xPedidosRoute = CentralAgons92xPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const CentralAgons92xObjetivosRoute =
  CentralAgons92xObjetivosRouteImport.update({
    id: '/objetivos',
    path: '/objetivos',
    getParentRoute: () => CentralAgons92xRoute,
  } as any)
const CentralAgons92xLogisticaRoute =
  CentralAgons92xLogisticaRouteImport.update({
    id: '/logistica',
    path: '/logistica',
    getParentRoute: () => CentralAgons92xRoute,
  } as any)
const CentralAgons92xKitsRoute = CentralAgons92xKitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const CentralAgons92xHomeRoute = CentralAgons92xHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const CentralAgons92xEsqueciSenhaRoute =
  CentralAgons92xEsqueciSenhaRouteImport.update({
    id: '/esqueci-senha',
    path: '/esqueci-senha',
    getParentRoute: () => CentralAgons92xRoute,
  } as any)
const CentralAgons92xEntrarRoute = CentralAgons92xEntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const CentralAgons92xEmporioRoute = CentralAgons92xEmporioRouteImport.update({
  id: '/emporio',
  path: '/emporio',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const CentralAgons92xCuponsRoute = CentralAgons92xCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const CentralAgons92xConteudoRoute = CentralAgons92xConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const CentralAgons92xClientesRoute = CentralAgons92xClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const CentralAgons92xCategoriasRoute =
  CentralAgons92xCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => CentralAgons92xRoute,
  } as any)
const CentralAgons92xCalendarioRoute =
  CentralAgons92xCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => CentralAgons92xRoute,
  } as any)
const CentralAgons92xBannersRoute = CentralAgons92xBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => CentralAgons92xRoute,
} as any)
const CentralAgons92xAparenciaRoute =
  CentralAgons92xAparenciaRouteImport.update({
    id: '/aparencia',
    path: '/aparencia',
    getParentRoute: () => CentralAgons92xRoute,
  } as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPasswordResetRoute = ApiPasswordResetRouteImport.update({
  id: '/api/password-reset',
  path: '/api/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmporioRoute = ApiEmporioRouteImport.update({
  id: '/api/emporio',
  path: '/api/emporio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeliveryCalendarRoute = ApiDeliveryCalendarRouteImport.update({
  id: '/api/delivery-calendar',
  path: '/api/delivery-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerSessionRoute = ApiCustomerSessionRouteImport.update({
  id: '/api/customer-session',
  path: '/api/customer-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerRegisterRoute = ApiCustomerRegisterRouteImport.update({
  id: '/api/customer-register',
  path: '/api/customer-register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerPasswordResetRoute =
  ApiCustomerPasswordResetRouteImport.update({
    id: '/api/customer-password-reset',
    path: '/api/customer-password-reset',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCustomerAccountRoute = ApiCustomerAccountRouteImport.update({
  id: '/api/customer-account',
  path: '/api/customer-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStateRoute = ApiAdminStateRouteImport.update({
  id: '/api/admin-state',
  path: '/api/admin-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSessionRoute = ApiAdminSessionRouteImport.update({
  id: '/api/admin-session',
  path: '/api/admin-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOperationsRoute = ApiAdminOperationsRouteImport.update({
  id: '/api/admin-operations',
  path: '/api/admin-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdRoute = ApiMediaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMediaRoute,
} as any)
const ApiEmporioIdRoute = ApiEmporioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiEmporioRoute,
} as any)
const ApiCheckoutSessionIdRoute = ApiCheckoutSessionIdRouteImport.update({
  id: '/api/checkout-session/$id',
  path: '/api/checkout-session/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cardapio': typeof CardapioRoute
  '/central-agons-92x': typeof CentralAgons92xRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/emporio': typeof EmporioRoute
  '/entregas': typeof EntregasRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/api/admin-operations': typeof ApiAdminOperationsRoute
  '/api/admin-session': typeof ApiAdminSessionRoute
  '/api/admin-state': typeof ApiAdminStateRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/customer-account': typeof ApiCustomerAccountRoute
  '/api/customer-password-reset': typeof ApiCustomerPasswordResetRoute
  '/api/customer-register': typeof ApiCustomerRegisterRoute
  '/api/customer-session': typeof ApiCustomerSessionRoute
  '/api/delivery-calendar': typeof ApiDeliveryCalendarRoute
  '/api/emporio': typeof ApiEmporioRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/api/orders': typeof ApiOrdersRoute
  '/api/password-reset': typeof ApiPasswordResetRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/central-agons-92x/aparencia': typeof CentralAgons92xAparenciaRoute
  '/central-agons-92x/banners': typeof CentralAgons92xBannersRoute
  '/central-agons-92x/calendario': typeof CentralAgons92xCalendarioRoute
  '/central-agons-92x/categorias': typeof CentralAgons92xCategoriasRoute
  '/central-agons-92x/clientes': typeof CentralAgons92xClientesRoute
  '/central-agons-92x/conteudo': typeof CentralAgons92xConteudoRoute
  '/central-agons-92x/cupons': typeof CentralAgons92xCuponsRoute
  '/central-agons-92x/emporio': typeof CentralAgons92xEmporioRoute
  '/central-agons-92x/entrar': typeof CentralAgons92xEntrarRoute
  '/central-agons-92x/esqueci-senha': typeof CentralAgons92xEsqueciSenhaRoute
  '/central-agons-92x/home': typeof CentralAgons92xHomeRoute
  '/central-agons-92x/kits': typeof CentralAgons92xKitsRoute
  '/central-agons-92x/logistica': typeof CentralAgons92xLogisticaRoute
  '/central-agons-92x/objetivos': typeof CentralAgons92xObjetivosRoute
  '/central-agons-92x/pedidos': typeof CentralAgons92xPedidosRoute
  '/central-agons-92x/producao': typeof CentralAgons92xProducaoRoute
  '/central-agons-92x/produtos': typeof CentralAgons92xProdutosRoute
  '/central-agons-92x/redefinir-senha': typeof CentralAgons92xRedefinirSenhaRoute
  '/central-agons-92x/relatorios': typeof CentralAgons92xRelatoriosRoute
  '/kit/$slug': typeof KitSlugRoute
  '/objetivo/$slug': typeof ObjetivoSlugRoute
  '/pedido/confirmado': typeof PedidoConfirmadoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/central-agons-92x/': typeof CentralAgons92xIndexRoute
  '/api/checkout-session/$id': typeof ApiCheckoutSessionIdRoute
  '/api/emporio/$id': typeof ApiEmporioIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cardapio': typeof CardapioRoute
  '/checkout': typeof CheckoutRoute
  '/emporio': typeof EmporioRoute
  '/entregas': typeof EntregasRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/api/admin-operations': typeof ApiAdminOperationsRoute
  '/api/admin-session': typeof ApiAdminSessionRoute
  '/api/admin-state': typeof ApiAdminStateRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/customer-account': typeof ApiCustomerAccountRoute
  '/api/customer-password-reset': typeof ApiCustomerPasswordResetRoute
  '/api/customer-register': typeof ApiCustomerRegisterRoute
  '/api/customer-session': typeof ApiCustomerSessionRoute
  '/api/delivery-calendar': typeof ApiDeliveryCalendarRoute
  '/api/emporio': typeof ApiEmporioRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/api/orders': typeof ApiOrdersRoute
  '/api/password-reset': typeof ApiPasswordResetRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/central-agons-92x/aparencia': typeof CentralAgons92xAparenciaRoute
  '/central-agons-92x/banners': typeof CentralAgons92xBannersRoute
  '/central-agons-92x/calendario': typeof CentralAgons92xCalendarioRoute
  '/central-agons-92x/categorias': typeof CentralAgons92xCategoriasRoute
  '/central-agons-92x/clientes': typeof CentralAgons92xClientesRoute
  '/central-agons-92x/conteudo': typeof CentralAgons92xConteudoRoute
  '/central-agons-92x/cupons': typeof CentralAgons92xCuponsRoute
  '/central-agons-92x/emporio': typeof CentralAgons92xEmporioRoute
  '/central-agons-92x/entrar': typeof CentralAgons92xEntrarRoute
  '/central-agons-92x/esqueci-senha': typeof CentralAgons92xEsqueciSenhaRoute
  '/central-agons-92x/home': typeof CentralAgons92xHomeRoute
  '/central-agons-92x/kits': typeof CentralAgons92xKitsRoute
  '/central-agons-92x/logistica': typeof CentralAgons92xLogisticaRoute
  '/central-agons-92x/objetivos': typeof CentralAgons92xObjetivosRoute
  '/central-agons-92x/pedidos': typeof CentralAgons92xPedidosRoute
  '/central-agons-92x/producao': typeof CentralAgons92xProducaoRoute
  '/central-agons-92x/produtos': typeof CentralAgons92xProdutosRoute
  '/central-agons-92x/redefinir-senha': typeof CentralAgons92xRedefinirSenhaRoute
  '/central-agons-92x/relatorios': typeof CentralAgons92xRelatoriosRoute
  '/kit/$slug': typeof KitSlugRoute
  '/objetivo/$slug': typeof ObjetivoSlugRoute
  '/pedido/confirmado': typeof PedidoConfirmadoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/central-agons-92x': typeof CentralAgons92xIndexRoute
  '/api/checkout-session/$id': typeof ApiCheckoutSessionIdRoute
  '/api/emporio/$id': typeof ApiEmporioIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cardapio': typeof CardapioRoute
  '/central-agons-92x': typeof CentralAgons92xRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/emporio': typeof EmporioRoute
  '/entregas': typeof EntregasRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/api/admin-operations': typeof ApiAdminOperationsRoute
  '/api/admin-session': typeof ApiAdminSessionRoute
  '/api/admin-state': typeof ApiAdminStateRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/customer-account': typeof ApiCustomerAccountRoute
  '/api/customer-password-reset': typeof ApiCustomerPasswordResetRoute
  '/api/customer-register': typeof ApiCustomerRegisterRoute
  '/api/customer-session': typeof ApiCustomerSessionRoute
  '/api/delivery-calendar': typeof ApiDeliveryCalendarRoute
  '/api/emporio': typeof ApiEmporioRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/api/orders': typeof ApiOrdersRoute
  '/api/password-reset': typeof ApiPasswordResetRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/central-agons-92x/aparencia': typeof CentralAgons92xAparenciaRoute
  '/central-agons-92x/banners': typeof CentralAgons92xBannersRoute
  '/central-agons-92x/calendario': typeof CentralAgons92xCalendarioRoute
  '/central-agons-92x/categorias': typeof CentralAgons92xCategoriasRoute
  '/central-agons-92x/clientes': typeof CentralAgons92xClientesRoute
  '/central-agons-92x/conteudo': typeof CentralAgons92xConteudoRoute
  '/central-agons-92x/cupons': typeof CentralAgons92xCuponsRoute
  '/central-agons-92x/emporio': typeof CentralAgons92xEmporioRoute
  '/central-agons-92x/entrar': typeof CentralAgons92xEntrarRoute
  '/central-agons-92x/esqueci-senha': typeof CentralAgons92xEsqueciSenhaRoute
  '/central-agons-92x/home': typeof CentralAgons92xHomeRoute
  '/central-agons-92x/kits': typeof CentralAgons92xKitsRoute
  '/central-agons-92x/logistica': typeof CentralAgons92xLogisticaRoute
  '/central-agons-92x/objetivos': typeof CentralAgons92xObjetivosRoute
  '/central-agons-92x/pedidos': typeof CentralAgons92xPedidosRoute
  '/central-agons-92x/producao': typeof CentralAgons92xProducaoRoute
  '/central-agons-92x/produtos': typeof CentralAgons92xProdutosRoute
  '/central-agons-92x/redefinir-senha': typeof CentralAgons92xRedefinirSenhaRoute
  '/central-agons-92x/relatorios': typeof CentralAgons92xRelatoriosRoute
  '/kit/$slug': typeof KitSlugRoute
  '/objetivo/$slug': typeof ObjetivoSlugRoute
  '/pedido/confirmado': typeof PedidoConfirmadoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/central-agons-92x/': typeof CentralAgons92xIndexRoute
  '/api/checkout-session/$id': typeof ApiCheckoutSessionIdRoute
  '/api/emporio/$id': typeof ApiEmporioIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/cardapio'
    | '/central-agons-92x'
    | '/checkout'
    | '/emporio'
    | '/entregas'
    | '/esqueci-senha'
    | '/login'
    | '/minha-conta'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/api/admin-operations'
    | '/api/admin-session'
    | '/api/admin-state'
    | '/api/checkout'
    | '/api/customer-account'
    | '/api/customer-password-reset'
    | '/api/customer-register'
    | '/api/customer-session'
    | '/api/delivery-calendar'
    | '/api/emporio'
    | '/api/health'
    | '/api/media'
    | '/api/orders'
    | '/api/password-reset'
    | '/api/stripe-webhook'
    | '/categoria/$slug'
    | '/central-agons-92x/aparencia'
    | '/central-agons-92x/banners'
    | '/central-agons-92x/calendario'
    | '/central-agons-92x/categorias'
    | '/central-agons-92x/clientes'
    | '/central-agons-92x/conteudo'
    | '/central-agons-92x/cupons'
    | '/central-agons-92x/emporio'
    | '/central-agons-92x/entrar'
    | '/central-agons-92x/esqueci-senha'
    | '/central-agons-92x/home'
    | '/central-agons-92x/kits'
    | '/central-agons-92x/logistica'
    | '/central-agons-92x/objetivos'
    | '/central-agons-92x/pedidos'
    | '/central-agons-92x/producao'
    | '/central-agons-92x/produtos'
    | '/central-agons-92x/redefinir-senha'
    | '/central-agons-92x/relatorios'
    | '/kit/$slug'
    | '/objetivo/$slug'
    | '/pedido/confirmado'
    | '/produto/$slug'
    | '/central-agons-92x/'
    | '/api/checkout-session/$id'
    | '/api/emporio/$id'
    | '/api/media/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/cardapio'
    | '/checkout'
    | '/emporio'
    | '/entregas'
    | '/esqueci-senha'
    | '/login'
    | '/minha-conta'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/api/admin-operations'
    | '/api/admin-session'
    | '/api/admin-state'
    | '/api/checkout'
    | '/api/customer-account'
    | '/api/customer-password-reset'
    | '/api/customer-register'
    | '/api/customer-session'
    | '/api/delivery-calendar'
    | '/api/emporio'
    | '/api/health'
    | '/api/media'
    | '/api/orders'
    | '/api/password-reset'
    | '/api/stripe-webhook'
    | '/categoria/$slug'
    | '/central-agons-92x/aparencia'
    | '/central-agons-92x/banners'
    | '/central-agons-92x/calendario'
    | '/central-agons-92x/categorias'
    | '/central-agons-92x/clientes'
    | '/central-agons-92x/conteudo'
    | '/central-agons-92x/cupons'
    | '/central-agons-92x/emporio'
    | '/central-agons-92x/entrar'
    | '/central-agons-92x/esqueci-senha'
    | '/central-agons-92x/home'
    | '/central-agons-92x/kits'
    | '/central-agons-92x/logistica'
    | '/central-agons-92x/objetivos'
    | '/central-agons-92x/pedidos'
    | '/central-agons-92x/producao'
    | '/central-agons-92x/produtos'
    | '/central-agons-92x/redefinir-senha'
    | '/central-agons-92x/relatorios'
    | '/kit/$slug'
    | '/objetivo/$slug'
    | '/pedido/confirmado'
    | '/produto/$slug'
    | '/central-agons-92x'
    | '/api/checkout-session/$id'
    | '/api/emporio/$id'
    | '/api/media/$id'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/cardapio'
    | '/central-agons-92x'
    | '/checkout'
    | '/emporio'
    | '/entregas'
    | '/esqueci-senha'
    | '/login'
    | '/minha-conta'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/api/admin-operations'
    | '/api/admin-session'
    | '/api/admin-state'
    | '/api/checkout'
    | '/api/customer-account'
    | '/api/customer-password-reset'
    | '/api/customer-register'
    | '/api/customer-session'
    | '/api/delivery-calendar'
    | '/api/emporio'
    | '/api/health'
    | '/api/media'
    | '/api/orders'
    | '/api/password-reset'
    | '/api/stripe-webhook'
    | '/categoria/$slug'
    | '/central-agons-92x/aparencia'
    | '/central-agons-92x/banners'
    | '/central-agons-92x/calendario'
    | '/central-agons-92x/categorias'
    | '/central-agons-92x/clientes'
    | '/central-agons-92x/conteudo'
    | '/central-agons-92x/cupons'
    | '/central-agons-92x/emporio'
    | '/central-agons-92x/entrar'
    | '/central-agons-92x/esqueci-senha'
    | '/central-agons-92x/home'
    | '/central-agons-92x/kits'
    | '/central-agons-92x/logistica'
    | '/central-agons-92x/objetivos'
    | '/central-agons-92x/pedidos'
    | '/central-agons-92x/producao'
    | '/central-agons-92x/produtos'
    | '/central-agons-92x/redefinir-senha'
    | '/central-agons-92x/relatorios'
    | '/kit/$slug'
    | '/objetivo/$slug'
    | '/pedido/confirmado'
    | '/produto/$slug'
    | '/central-agons-92x/'
    | '/api/checkout-session/$id'
    | '/api/emporio/$id'
    | '/api/media/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CardapioRoute: typeof CardapioRoute
  CentralAgons92xRoute: typeof CentralAgons92xRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  EmporioRoute: typeof EmporioRoute
  EntregasRoute: typeof EntregasRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  MinhaContaRoute: typeof MinhaContaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  TermosRoute: typeof TermosRoute
  ApiAdminOperationsRoute: typeof ApiAdminOperationsRoute
  ApiAdminSessionRoute: typeof ApiAdminSessionRoute
  ApiAdminStateRoute: typeof ApiAdminStateRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiCustomerAccountRoute: typeof ApiCustomerAccountRoute
  ApiCustomerPasswordResetRoute: typeof ApiCustomerPasswordResetRoute
  ApiCustomerRegisterRoute: typeof ApiCustomerRegisterRoute
  ApiCustomerSessionRoute: typeof ApiCustomerSessionRoute
  ApiDeliveryCalendarRoute: typeof ApiDeliveryCalendarRoute
  ApiEmporioRoute: typeof ApiEmporioRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMediaRoute: typeof ApiMediaRouteWithChildren
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiPasswordResetRoute: typeof ApiPasswordResetRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  KitSlugRoute: typeof KitSlugRoute
  ObjetivoSlugRoute: typeof ObjetivoSlugRoute
  PedidoConfirmadoRoute: typeof PedidoConfirmadoRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiCheckoutSessionIdRoute: typeof ApiCheckoutSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregas': {
      id: '/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof EntregasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emporio': {
      id: '/emporio'
      path: '/emporio'
      fullPath: '/emporio'
      preLoaderRoute: typeof EmporioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central-agons-92x': {
      id: '/central-agons-92x'
      path: '/central-agons-92x'
      fullPath: '/central-agons-92x'
      preLoaderRoute: typeof CentralAgons92xRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio': {
      id: '/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof CardapioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central-agons-92x/': {
      id: '/central-agons-92x/'
      path: '/'
      fullPath: '/central-agons-92x/'
      preLoaderRoute: typeof CentralAgons92xIndexRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/confirmado': {
      id: '/pedido/confirmado'
      path: '/pedido/confirmado'
      fullPath: '/pedido/confirmado'
      preLoaderRoute: typeof PedidoConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objetivo/$slug': {
      id: '/objetivo/$slug'
      path: '/objetivo/$slug'
      fullPath: '/objetivo/$slug'
      preLoaderRoute: typeof ObjetivoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit/$slug': {
      id: '/kit/$slug'
      path: '/kit/$slug'
      fullPath: '/kit/$slug'
      preLoaderRoute: typeof KitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central-agons-92x/relatorios': {
      id: '/central-agons-92x/relatorios'
      path: '/relatorios'
      fullPath: '/central-agons-92x/relatorios'
      preLoaderRoute: typeof CentralAgons92xRelatoriosRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/redefinir-senha': {
      id: '/central-agons-92x/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/central-agons-92x/redefinir-senha'
      preLoaderRoute: typeof CentralAgons92xRedefinirSenhaRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/produtos': {
      id: '/central-agons-92x/produtos'
      path: '/produtos'
      fullPath: '/central-agons-92x/produtos'
      preLoaderRoute: typeof CentralAgons92xProdutosRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/producao': {
      id: '/central-agons-92x/producao'
      path: '/producao'
      fullPath: '/central-agons-92x/producao'
      preLoaderRoute: typeof CentralAgons92xProducaoRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/pedidos': {
      id: '/central-agons-92x/pedidos'
      path: '/pedidos'
      fullPath: '/central-agons-92x/pedidos'
      preLoaderRoute: typeof CentralAgons92xPedidosRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/objetivos': {
      id: '/central-agons-92x/objetivos'
      path: '/objetivos'
      fullPath: '/central-agons-92x/objetivos'
      preLoaderRoute: typeof CentralAgons92xObjetivosRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/logistica': {
      id: '/central-agons-92x/logistica'
      path: '/logistica'
      fullPath: '/central-agons-92x/logistica'
      preLoaderRoute: typeof CentralAgons92xLogisticaRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/kits': {
      id: '/central-agons-92x/kits'
      path: '/kits'
      fullPath: '/central-agons-92x/kits'
      preLoaderRoute: typeof CentralAgons92xKitsRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/home': {
      id: '/central-agons-92x/home'
      path: '/home'
      fullPath: '/central-agons-92x/home'
      preLoaderRoute: typeof CentralAgons92xHomeRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/esqueci-senha': {
      id: '/central-agons-92x/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/central-agons-92x/esqueci-senha'
      preLoaderRoute: typeof CentralAgons92xEsqueciSenhaRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/entrar': {
      id: '/central-agons-92x/entrar'
      path: '/entrar'
      fullPath: '/central-agons-92x/entrar'
      preLoaderRoute: typeof CentralAgons92xEntrarRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/emporio': {
      id: '/central-agons-92x/emporio'
      path: '/emporio'
      fullPath: '/central-agons-92x/emporio'
      preLoaderRoute: typeof CentralAgons92xEmporioRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/cupons': {
      id: '/central-agons-92x/cupons'
      path: '/cupons'
      fullPath: '/central-agons-92x/cupons'
      preLoaderRoute: typeof CentralAgons92xCuponsRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/conteudo': {
      id: '/central-agons-92x/conteudo'
      path: '/conteudo'
      fullPath: '/central-agons-92x/conteudo'
      preLoaderRoute: typeof CentralAgons92xConteudoRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/clientes': {
      id: '/central-agons-92x/clientes'
      path: '/clientes'
      fullPath: '/central-agons-92x/clientes'
      preLoaderRoute: typeof CentralAgons92xClientesRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/categorias': {
      id: '/central-agons-92x/categorias'
      path: '/categorias'
      fullPath: '/central-agons-92x/categorias'
      preLoaderRoute: typeof CentralAgons92xCategoriasRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/calendario': {
      id: '/central-agons-92x/calendario'
      path: '/calendario'
      fullPath: '/central-agons-92x/calendario'
      preLoaderRoute: typeof CentralAgons92xCalendarioRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/banners': {
      id: '/central-agons-92x/banners'
      path: '/banners'
      fullPath: '/central-agons-92x/banners'
      preLoaderRoute: typeof CentralAgons92xBannersRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/central-agons-92x/aparencia': {
      id: '/central-agons-92x/aparencia'
      path: '/aparencia'
      fullPath: '/central-agons-92x/aparencia'
      preLoaderRoute: typeof CentralAgons92xAparenciaRouteImport
      parentRoute: typeof CentralAgons92xRoute
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/password-reset': {
      id: '/api/password-reset'
      path: '/api/password-reset'
      fullPath: '/api/password-reset'
      preLoaderRoute: typeof ApiPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/emporio': {
      id: '/api/emporio'
      path: '/api/emporio'
      fullPath: '/api/emporio'
      preLoaderRoute: typeof ApiEmporioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delivery-calendar': {
      id: '/api/delivery-calendar'
      path: '/api/delivery-calendar'
      fullPath: '/api/delivery-calendar'
      preLoaderRoute: typeof ApiDeliveryCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-session': {
      id: '/api/customer-session'
      path: '/api/customer-session'
      fullPath: '/api/customer-session'
      preLoaderRoute: typeof ApiCustomerSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-register': {
      id: '/api/customer-register'
      path: '/api/customer-register'
      fullPath: '/api/customer-register'
      preLoaderRoute: typeof ApiCustomerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-password-reset': {
      id: '/api/customer-password-reset'
      path: '/api/customer-password-reset'
      fullPath: '/api/customer-password-reset'
      preLoaderRoute: typeof ApiCustomerPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-account': {
      id: '/api/customer-account'
      path: '/api/customer-account'
      fullPath: '/api/customer-account'
      preLoaderRoute: typeof ApiCustomerAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-state': {
      id: '/api/admin-state'
      path: '/api/admin-state'
      fullPath: '/api/admin-state'
      preLoaderRoute: typeof ApiAdminStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-session': {
      id: '/api/admin-session'
      path: '/api/admin-session'
      fullPath: '/api/admin-session'
      preLoaderRoute: typeof ApiAdminSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-operations': {
      id: '/api/admin-operations'
      path: '/api/admin-operations'
      fullPath: '/api/admin-operations'
      preLoaderRoute: typeof ApiAdminOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id': {
      id: '/api/media/$id'
      path: '/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdRouteImport
      parentRoute: typeof ApiMediaRoute
    }
    '/api/emporio/$id': {
      id: '/api/emporio/$id'
      path: '/$id'
      fullPath: '/api/emporio/$id'
      preLoaderRoute: typeof ApiEmporioIdRouteImport
      parentRoute: typeof ApiEmporioRoute
    }
    '/api/checkout-session/$id': {
      id: '/api/checkout-session/$id'
      path: '/api/checkout-session/$id'
      fullPath: '/api/checkout-session/$id'
      preLoaderRoute: typeof ApiCheckoutSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CentralAgons92xRouteChildren {
  CentralAgons92xAparenciaRoute: typeof CentralAgons92xAparenciaRoute
  CentralAgons92xBannersRoute: typeof CentralAgons92xBannersRoute
  CentralAgons92xCalendarioRoute: typeof CentralAgons92xCalendarioRoute
  CentralAgons92xCategoriasRoute: typeof CentralAgons92xCategoriasRoute
  CentralAgons92xClientesRoute: typeof CentralAgons92xClientesRoute
  CentralAgons92xConteudoRoute: typeof CentralAgons92xConteudoRoute
  CentralAgons92xCuponsRoute: typeof CentralAgons92xCuponsRoute
  CentralAgons92xEmporioRoute: typeof CentralAgons92xEmporioRoute
  CentralAgons92xEntrarRoute: typeof CentralAgons92xEntrarRoute
  CentralAgons92xEsqueciSenhaRoute: typeof CentralAgons92xEsqueciSenhaRoute
  CentralAgons92xHomeRoute: typeof CentralAgons92xHomeRoute
  CentralAgons92xKitsRoute: typeof CentralAgons92xKitsRoute
  CentralAgons92xLogisticaRoute: typeof CentralAgons92xLogisticaRoute
  CentralAgons92xObjetivosRoute: typeof CentralAgons92xObjetivosRoute
  CentralAgons92xPedidosRoute: typeof CentralAgons92xPedidosRoute
  CentralAgons92xProducaoRoute: typeof CentralAgons92xProducaoRoute
  CentralAgons92xProdutosRoute: typeof CentralAgons92xProdutosRoute
  CentralAgons92xRedefinirSenhaRoute: typeof CentralAgons92xRedefinirSenhaRoute
  CentralAgons92xRelatoriosRoute: typeof CentralAgons92xRelatoriosRoute
  CentralAgons92xIndexRoute: typeof CentralAgons92xIndexRoute
}

const CentralAgons92xRouteChildren: CentralAgons92xRouteChildren = {
  CentralAgons92xAparenciaRoute: CentralAgons92xAparenciaRoute,
  CentralAgons92xBannersRoute: CentralAgons92xBannersRoute,
  CentralAgons92xCalendarioRoute: CentralAgons92xCalendarioRoute,
  CentralAgons92xCategoriasRoute: CentralAgons92xCategoriasRoute,
  CentralAgons92xClientesRoute: CentralAgons92xClientesRoute,
  CentralAgons92xConteudoRoute: CentralAgons92xConteudoRoute,
  CentralAgons92xCuponsRoute: CentralAgons92xCuponsRoute,
  CentralAgons92xEmporioRoute: CentralAgons92xEmporioRoute,
  CentralAgons92xEntrarRoute: CentralAgons92xEntrarRoute,
  CentralAgons92xEsqueciSenhaRoute: CentralAgons92xEsqueciSenhaRoute,
  CentralAgons92xHomeRoute: CentralAgons92xHomeRoute,
  CentralAgons92xKitsRoute: CentralAgons92xKitsRoute,
  CentralAgons92xLogisticaRoute: CentralAgons92xLogisticaRoute,
  CentralAgons92xObjetivosRoute: CentralAgons92xObjetivosRoute,
  CentralAgons92xPedidosRoute: CentralAgons92xPedidosRoute,
  CentralAgons92xProducaoRoute: CentralAgons92xProducaoRoute,
  CentralAgons92xProdutosRoute: CentralAgons92xProdutosRoute,
  CentralAgons92xRedefinirSenhaRoute: CentralAgons92xRedefinirSenhaRoute,
  CentralAgons92xRelatoriosRoute: CentralAgons92xRelatoriosRoute,
  CentralAgons92xIndexRoute: CentralAgons92xIndexRoute,
}

const CentralAgons92xRouteWithChildren = CentralAgons92xRoute._addFileChildren(
  CentralAgons92xRouteChildren,
)

interface ApiEmporioRouteChildren {
  ApiEmporioIdRoute: typeof ApiEmporioIdRoute
}

const ApiEmporioRouteChildren: ApiEmporioRouteChildren = {
  ApiEmporioIdRoute: ApiEmporioIdRoute,
}

const ApiEmporioRouteWithChildren = ApiEmporioRoute._addFileChildren(
  ApiEmporioRouteChildren,
)

interface ApiMediaRouteChildren {
  ApiMediaIdRoute: typeof ApiMediaIdRoute
}

const ApiMediaRouteChildren: ApiMediaRouteChildren = {
  ApiMediaIdRoute: ApiMediaIdRoute,
}

const ApiMediaRouteWithChildren = ApiMediaRoute._addFileChildren(
  ApiMediaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CardapioRoute: CardapioRoute,
  CentralAgons92xRoute: CentralAgons92xRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  EmporioRoute: EmporioRoute,
  EntregasRoute: EntregasRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  MinhaContaRoute: MinhaContaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  TermosRoute: TermosRoute,
  ApiAdminOperationsRoute: ApiAdminOperationsRoute,
  ApiAdminSessionRoute: ApiAdminSessionRoute,
  ApiAdminStateRoute: ApiAdminStateRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiCustomerAccountRoute: ApiCustomerAccountRoute,
  ApiCustomerPasswordResetRoute: ApiCustomerPasswordResetRoute,
  ApiCustomerRegisterRoute: ApiCustomerRegisterRoute,
  ApiCustomerSessionRoute: ApiCustomerSessionRoute,
  ApiDeliveryCalendarRoute: ApiDeliveryCalendarRoute,
  ApiEmporioRoute: ApiEmporioRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiMediaRoute: ApiMediaRouteWithChildren,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiPasswordResetRoute: ApiPasswordResetRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  KitSlugRoute: KitSlugRoute,
  ObjetivoSlugRoute: ObjetivoSlugRoute,
  PedidoConfirmadoRoute: PedidoConfirmadoRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiCheckoutSessionIdRoute: ApiCheckoutSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
